### ISSUE TITLE
Feed handling, why RCurl dep and github install link

### ISSUE THREAD

**Issue by hrbrmstr** [RobertMyles/tidyRSS#1]
Congrats on the CRAN submission!

However…

Neither of these worked (the first 2 things I tried):

    tidyfeed("https://rud.is/b/feed/")

    tidyfeed("https://rweekly.org/atom.xml")

Those are totally valid feed that work in every RSS reader but not in your pkg.

`xml2` already `Suggests` `curl` and `httr` and most folks who are likely to use this pkg  have the `tidyverse` installed. `RCurl` adds a somewhat needless dep onto systems.

And:

    devtools::install_github("https://github.com/RobertMyles/tidyrss")

should be

    devtools::install_github("RobertMyles/tidyrss")

**Comment by RobertMyles** [comment]
Thanks @hrbrmstr. I was actually using curl and httr and I had the package ready, until I discovered it didn't work with some rss feeds, so I switched to RCurl, which did work with them. Thanks for the report, I'll get it fixed asap.
