### ISSUE TITLE
"evaluation failed" for RSS from Austria

### ISSUE THREAD

**Issue by mbflex** [RobertMyles/tidyRSS#11]
`library(tidyRSS)`
`rss <- tidyfeed("http://derStandard.at/?page=rss&ressort=Newsroom") `

results in many error messages: 'xmlXPathEval: evaluation failed'

**Comment by RobertMyles** [comment]
Hi, these are warnings and not errors as such. `tidyRSS()` is searching for parameters (such as "author") that may or not exist in the feed, if they don't exist, you get this message. I've been meaning to clean it up, will do in a future release.
