### ISSUE TITLE
xml error

### ISSUE THREAD

**Issue by YoungjunNa** [RobertMyles/tidyRSS#16]
I have tried like that:
tidyRSS::tidyfeed("https://academic.oup.com/rss/site_6148/3994.xml")

An error message appear:
Error in doc$headers : $ operator is invalid for atomic vectors

Thank you.

**Comment by RobertMyles** [comment]
Gives me a curl error: 

``` r
httr::GET("https://academic.oup.com/rss/site_6148/3994.xml")
#> Error in curl::curl_fetch_memory(url, handle = handle): LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

Created on 2018-09-15 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

Not sure how to fix that, I'm afraid -- I've updated curl and httr, with no difference.
