### ISSUE TITLE
item_description not clean (contains html tags)

### ISSUE THREAD

**Issue by MoritzLaurer** [RobertMyles/tidyRSS#19]
Hi Robert, thanks again for your great package!

my issue: some data frames created by the "tidyfeed" function contain html tags in the "item_description" column. See for example: 
taz_df <- tidyfeed("http://www.taz.de/!p4615;rss/")
bild_df <- tidyfeed("https://www.bild.de/rssfeeds/vw-politik/vw-politik-16728980,view=rss2.bild.xml")
taz_df$item_description
bild_df$item_description

I found a function on stackoverflow which can clean the html tags away:   
cleanfun <- function(htmlString) { 
  return(gsub("<.*?>", "", htmlString))}
cleanfun(taz_df$item_description)   # html tags are gone.
See source: https://stackoverflow.com/questions/17227294/removing-html-tags-from-a-string-in-r
(I'm not sure if this is the best solution)

is there maybe a possibility to implement this (or any other solution) into tidyRSS? I could do the cleaning separately, but maybe you have the time to implement this into tidyRSS directly?

thank you very much!
Moritz

**Comment by RobertMyles** [comment]
Hi Moritz,

I took a closer look, and it's the original feed that is the problem here. If you compare the description in the feed you link to above with that of the Guardian, for example, you'll see the problem: 

http://www.taz.de/!p4615;rss/:

```
<description>
<![CDATA[
<a href="http://www.taz.de/Kolumne-Macht/!5553739/"><img align="left" style="margin-right:5px;" src="http://www.taz.de/picture/3120957/192/Buntstifte-Imago.jpeg" border="0" width="152" height="76" /></a> Unflätige Beschimpfungen, massive Bedrohungen – im politischen Raum verroht die Gesprächskultur. Aber es formiert sich eine Gegenbewegung. <a href="http://www.taz.de/Kolumne-Macht/!5553739/">mehr...</a>
]]>
</description>
```

https://www.theguardian.com/world/rss

```
<description>
<p>PM’s plan heading for huge defeat as senior Tory suggests second referendum could be her ‘only chance’</p><p>A deep cabinet split has opened up over whether Theresa May should back a <a href="https://www.theguardian.com/commentisfree/2018/nov/23/peoples-vote-brexit-mps-second-referendum" title="">second referendum </a>in a final attempt to end the political deadlock over Brexit, as senior Conservatives predicted on Saturday night that her blueprint for leaving the EU was heading for a crushing House of Commons defeat.</p><p>Adding to a mounting sense of constitutional crisis ahead of Tuesday’s crucial parliamentary vote, No 10 is braced for more resignations of ministers and aides who want another referendum, or who believe May’s deal fails to deliver on Brexit. Will Quince, the Colchester MP and aide to the defence secretary, Gavin Williamson, quit his post on Saturday night in protest at the Brexit deal.</p> <a href="https://www.theguardian.com/politics/2018/dec/08/cabinet-split-second-referendum-brexit">Continue reading...</a>
</description>
```

Including a feed-specific solution in tidyRSS isn't a good idea, so you will need to extract the content using regex. I've found the [strex](https://github.com/rorynolan/strex) package to be a very useful!

**Comment by MoritzLaurer** [comment]
Hi Robert, 
ok, understand, thanks for looking into it! :)
