### ISSUE TITLE
A url doesn't work

### ISSUE THREAD

**Issue by double-y** [RobertMyles/tidyRSS#2]
Hi, thank you for this great R package 😄 

I found a url that doesn't return anything. Could you support it?
https://www.wrike.com/rss/42acd7c449ad444c8ccea977f83413be

**Comment by RobertMyles** [comment]
Sure, @double-y ! I'll get working on it as soon as I can. Thanks for filing the issue!

**Comment by RobertMyles** [comment]
Are you sure this a feed, @double-y ? I get this when I go to that address:  

`{"success":false,"messageKey":"i18n.workspacemessages.no_rss_feature","message":"No RSS feature","mayRetry":false,"ex":null}`
