### ISSUE TITLE
Error loading library

### ISSUE THREAD

**Issue by PeterRochat** [RobertMyles/tidyRSS#22]
After installation I try to load the library but it fails:

Error: package or namespace load failed for ‘tidyRSS’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found

What is going wrong?

**Comment by RobertMyles** [comment]
Hi Peter, see #20 . Closing this, let me know if the solution there works for you or not.
