### ISSUE TITLE
Cannot generate feed

### ISSUE THREAD

**Issue by AforAmateur** [RobertMyles/tidyRSS#23]
Receiving Error: $ operator is invalid for atomic vectors all all kinds of feeds. :(

> rss <- tidyfeed("http://feeds.bbci.co.uk/news/rss.xml")
Error: $ operator is invalid for atomic vectors
> rss <- tidyfeed("http://andrewgelman.com/feed/")
Error: $ operator is invalid for atomic vectors
>

**Comment by RobertMyles** [comment]
Hi @AforAmateur , thanks for the issue report, I'll look into asap.

**Comment by AforAmateur** [comment]
> Hi @AforAmateur , thanks for the issue report, I'll look into asap.

Thanks -  Appreciate you looking into it.

**Comment by RobertMyles** [comment]
Can you check your settings, @AforAmateur ? I ran those two examples: 

<img width="1054" alt="Screen Shot 2019-04-30 at 18 40 47" src="https://user-images.githubusercontent.com/7211207/56981742-9107d280-6b77-11e9-8e5c-0986330ddd2e.png">

They're OK for me. Have you installed the latest version of the package?

**Comment by AforAmateur** [comment]
I tried and tried and tried then I uninstalled and installed R in a separate directory, that seems to have resolved the issue. Looks like the problem was at my end. Sorry for the trouble and thanks too!

**Comment by RobertMyles** [comment]
No problem, thanks for using the package!
