### ISSUE TITLE
Error in eval(lhs, parent, parent) : object 'rss' not found

### ISSUE THREAD

**Issue by ddbs** [RobertMyles/tidyRSS#25]
From the documentation example:  

`rss <- tidyfeed("http://fivethirtyeight.com/all/feed")`

is giving

`Error in eval(lhs, parent, parent) : object 'rss' not found`

This is happening for all rss/xml feeds.

**Comment by RobertMyles** [comment]
Thanks for flagging this @ddbs . Not sure how this happened, will have a fix asap.
