### ISSUE TITLE
Error: object 'rss' not found

### ISSUE THREAD

**Issue by DominiqueMakowski** [RobertMyles/tidyRSS#26]
Hi. This line of code worked until I've reinstalled the package, where it fails as follows:
``` r
tidyRSS::tidyfeed("https://easystats.github.io/blog/categories/r/index.xml")
#> Error in eval(lhs, parent, parent): object 'rss' not found
```

<sup>Created on 2019-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is that expected? Thanks for your package!

**Comment by RobertMyles** [comment]
Hi Dominique, this is a bug. Install the dev version with `devtools:: install_github("RobertMyles/tidyRSS")` and it should work fine!

**Comment by DominiqueMakowski** [comment]
I confirm it works with the github version :)

**Comment by RobertMyles** [comment]
Great, thanks :smile:
