### ISSUE TITLE
Error in eval(lhs, parent, parent) : object 'rss' not found

### ISSUE THREAD

**Issue by fenkod** [RobertMyles/tidyRSS#27]
I was receiving the message `Error in eval(lhs, parent, parent) : object 'rss' not found` when running the following `pitcher_list <- tidyRSS::tidyfeed("https://www.pitcherlist.com/feed")`.

Seeing other opened issues, I removed the tidyRSS package and installed using devtools from Github instead of CRAN. The following was run `devtools::install_github("RobertMyles/tidyRSS")`. The same error remained after a re-install.

**Comment by RobertMyles** [comment]
Hi David, thanks for reporting this. I wasn't able to reproduce it on my end: 

<img width="1160" alt="Screen Shot 2019-05-22 at 20 32 05" src="https://user-images.githubusercontent.com/7211207/58202927-cca64000-7cd0-11e9-96a1-11f35f66fc6b.png">

However, I've submitted the package to CRAN and it has passed the checks so hopefully you will be able to get it from there and this feed will work fine. I'm closing this, but if the problem persists, let me know.
