### ISSUE TITLE
Some RSS feeds return 403 error - here is a possible fix

### ISSUE THREAD

**Issue by tombroekel** [RobertMyles/tidyRSS#28]
I came across some RSS feeds that produce an error of this sort when using tidyRSS

Response [https://www.naumburger-tageblatt.de/feed/nachrichten/index.rss]
  Date: 2019-08-29 12:36
  Status: 403
  Content-Type: text/html
  Size: 94 B
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

---------------------------------------------------

Drawing on the feedeR package, which didn't produce this issue, I've implemented the following into the tidyfeed function. Maybe not the most elegant, but it seems to work.

doc <- try(httr::GET(feed, config), silent = TRUE)
      if(grepl("403", doc$status_code))
        {
        XMLFILE = tempfile(fileext = "-index.xml")
        options(HTTPUserAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36")
        download.file(url = clean.url(feed),XMLFILE,quiet = TRUE)
        doc<-xml2::read_xml(XMLFILE)
        }else if(grepl("json", doc$headers$`content-type`)){
        result <- json_parse(feed)
        return(result)
      } else{
        doc <- doc %>% xml2::read_xml()
      }

**Comment by RobertMyles** [comment]
Hi Tom, 
Did you try using the config argument to `httr::GET()` to pass these in?

**Comment by tombroekel** [comment]
Hi Robert,

No I did not because I am far from being an expert and I don’t know what caused this issue. Just noticed that the feedeR was able to deal with it. I am very much open to better solutions. Interestingly, the error was not consistent, so sometimes it worked but many times it did not. This is the troubling feed: https://www.naumburger-tageblatt.de/feed/nachrichten/index.rss

Kind regards,

Tom


____________________

Tom Broekel | Associate Professor of Regional Innovation | UiS Business School | Norway | t<mailto:tombroekel@me.com>om.broekel@uis.no<mailto:om.broekel@uis.no> | http://www.tombroekel.de  |

Recent publication: Broekel, T. (2019). Using structural diversity to measure the complexity of technologies. PLoS ONE, 14(5), 1–27. https://doi.org/10.1371/journal.pone.0216856

On 29 Aug 2019, at 15:12, Robert Myles McDonnell <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Tom,
Did you try using the config argument to httr::GET() to pass these in?

**Comment by RobertMyles** [comment]
Sure, totally understand! I'll check this more thoroughly as soon as I can and get back to you. If we can't fix it within `GET()`, I'll see how I can incorporate your suggested workaround.
Thanks,
Robert

**Comment by tombroekel** [comment]
Hi Robert,

Thanks. As “my solution” seems to work fine (and is just an additional if() condition in the tidyfeed function, I am not in a hurry. Nevertheless, thanks a lot for this beautiful package. You have no idea how much it is helping me.

Best,

Tom

____________________

Tom Broekel | Associate Professor of Regional Innovation | UiS Business School | Norway | t<mailto:tombroekel@me.com>om.broekel@uis.no<mailto:om.broekel@uis.no> | http://www.tombroekel.de  |

Recent publication: Broekel, T. (2019). Using structural diversity to measure the complexity of technologies. PLoS ONE, 14(5), 1–27. https://doi.org/10.1371/journal.pone.0216856

On 29 Aug 2019, at 15:30, Robert Myles McDonnell <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, totally understand! I'll check this more thoroughly as soon as I can and get back to you. If we can't fix it within GET(), I'll see how I can incorporate your suggested workaround.
Thanks,
Robert

**Comment by RobertMyles** [comment]
Happy to hear that, Tom! :-)

I've updated the package now to send a user agent with each request.  It seems to be working fine now:

```
> tidyfeed("https://www.naumburger-tageblatt.de/feed/nachrichten/index.rss")
# A tibble: 37 x 11
   feed_title feed_link feed_description feed_language feed_update_per… item_title item_creator
   <chr>      <chr>     <chr>            <chr>         <chr>            <chr>      <chr>       
 1 Naumburge… https://… Nachrichten, Be… de-de         ""               Bei Hochz… ""          
 2 Naumburge… https://… Nachrichten, Be… de-de         ""               Liveblog … ""          
 3 Naumburge… https://… Nachrichten, Be… de-de         ""               Brennende… ""          
 4 Naumburge… https://… Nachrichten, Be… de-de         ""               Angriff d… ""          
 5 Naumburge… https://… Nachrichten, Be… de-de         ""               Auf dem W… ""          
 6 Naumburge… https://… Nachrichten, Be… de-de         ""               Notkaiser… ""          
 7 Naumburge… https://… Nachrichten, Be… de-de         ""               Horoskop … ""          
 8 Naumburge… https://… Nachrichten, Be… de-de         ""               Karriere:… ""          
 9 Naumburge… https://… Nachrichten, Be… de-de         ""               LED-Leinw… ""          
10 Naumburge… https://… Nachrichten, Be… de-de         ""               Verkehrsk… ""          
# … with 27 more rows, and 4 more variables: item_date_published <dttm>, item_description <chr>,
#   item_link <chr>, item_categories <list>
```

Slight issue with the empty columns (they should be NA and then removed) but I'll see if I can fix that in a future release. 
I'll submit this to CRAN in the next few days, but in the meantime you can install this dev version and it should fix your problem. 
Thanks for the suggested fix, by the way, it was that that pointed to the user agent being the problem, so I wouldn't have known that otherwise 👍

**Comment by tombroekel** [comment]
Dear Robert,

It seems to work great now! Thanks a lot! Btw, do you work with RSS-Feed data and if so - what are you doing with it?

Best,

Tom

____________________

Tom Broekel | Associate Professor of Regional Innovation | UiS Business School | Norway | t<mailto:tombroekel@me.com>om.broekel@uis.no<mailto:om.broekel@uis.no> | http://www.tombroekel.de  |

Recent publication: Broekel, T. (2019). Using structural diversity to measure the complexity of technologies. PLoS ONE, 14(5), 1–27. https://doi.org/10.1371/journal.pone.0216856

On 1 Sep 2019, at 14:28, Robert Myles McDonnell <notifications@github.com<mailto:notifications@github.com>> wrote:


Happy to hear that, Tom! :-)

I've updated the package now to send a user agent with each request. It seems to be working fine now:

> tidyfeed("https://www.naumburger-tageblatt.de/feed/nachrichten/index.rss")
# A tibble: 37 x 11
   feed_title feed_link feed_description feed_language feed_update_per… item_title item_creator
   <chr>      <chr>     <chr>            <chr>         <chr>            <chr>      <chr>
 1 Naumburge… https://… Nachrichten, Be… de-de         ""               Bei Hochz… ""
 2 Naumburge… https://… Nachrichten, Be… de-de         ""               Liveblog … ""
 3 Naumburge… https://… Nachrichten, Be… de-de         ""               Brennende… ""
 4 Naumburge… https://… Nachrichten, Be… de-de         ""               Angriff d… ""
 5 Naumburge… https://… Nachrichten, Be… de-de         ""               Auf dem W… ""
 6 Naumburge… https://… Nachrichten, Be… de-de         ""               Notkaiser… ""
 7 Naumburge… https://… Nachrichten, Be… de-de         ""               Horoskop … ""
 8 Naumburge… https://… Nachrichten, Be… de-de         ""               Karriere:… ""
 9 Naumburge… https://… Nachrichten, Be… de-de         ""               LED-Leinw… ""
10 Naumburge… https://… Nachrichten, Be… de-de         ""               Verkehrsk… ""
# … with 27 more rows, and 4 more variables: item_date_published <dttm>, item_description <chr>,
#   item_link <chr>, item_categories <list>


Slight issue with the empty columns (they should be NA and then removed) but I'll see if I can fix that in a future release.
I'll submit this to CRAN in the next few days, but in the meantime you can install this dev version and it should fix your problem.
Thanks for the suggested fix, by the way, it was that that pointed to the user agent being the problem, so I wouldn't have known that otherwise 👍

**Comment by RobertMyles** [comment]
Great, happy to hear it's working.

I don't work with RSS data regularly, in fact I created the package because I was working with this type of data a while ago and I wanted tidy dataframes back, as opposed to the lists you get with feeder. It was a little Shiny app if I remember correctly. Do anything interesting with this data yourself?

**Comment by tombroekel** [comment]
Hi Robert,

Well, I am building up a news database based on RSS-Feeds. Scrapping a large number of non-uniform websites is beyond my capabilities. Therefore, RSS comes in handy, as surprisingly many newspapers (still) make use of this feature. Currently, I am concentrating on German speaking countries, but will soon expand. By now, I am reading >2k RSS feeds with your package, so it is in heavy use ;-)

Best,

Tom

____________________

Tom Broekel | Associate Professor of Regional Innovation | UiS Business School | Norway | t<mailto:tombroekel@me.com>om.broekel@uis.no<mailto:om.broekel@uis.no> | http://www.tombroekel.de  |

Recent publication: Broekel, T. (2019). Using structural diversity to measure the complexity of technologies. PLoS ONE, 14(5), 1–27. https://doi.org/10.1371/journal.pone.0216856

On 5 Sep 2019, at 10:48, Robert Myles McDonnell <notifications@github.com<mailto:notifications@github.com>> wrote:


Great, happy to hear it's working.

I don't work with RSS data regularly, in fact I created the package because I was working with this type of data a while ago and I wanted tidy dataframes back, as opposed to the lists you get with feeder. It was a little Shiny app if I remember correctly. Do anything interesting with this data yourself?

**Comment by RobertMyles** [comment]
That sounds very interesting, Tom. Best of luck with the project!

**Comment by rxtx240** [comment]
I have had a similar issue trying to return the feed from the following URLs
tidyfeed("https://agenciadenoticias.ibge.gov.br/agencia-rss")
Error in read_xml.response(.) : Forbidden (HTTP 403).

tidyfeed("https://conteudo.bcb.gov.br/api/feed/pt-br/notas?ano=2019")
Error: $ operator is invalid for atomic vectors

**Comment by RobertMyles** [comment]
Hi @rxtx240 
Is this an authentication issue for the first one? Have you looked into using httr's config options? These are available for use with `tidyfeed()`. 

As for the second feed, it works fine for me:

```r
> tidyRSS::tidyfeed("https://conteudo.bcb.gov.br/api/feed/pt-br/notas?ano=2019")
# A tibble: 224 x 7
   feed_title  feed_link    feed_last_updated  item_title                   item_date_updated   item_link      item_content
   <chr>       <chr>        <chr>              <chr>                        <dttm>              <chr>          <chr>       
 1 Notas à im… https://www… 2019-10-23T12:54:… Apresentação do Presidente … 2019-10-17 17:31:22 https://www.b… ""          
 2 Notas à im… https://www… 2019-10-23T12:54:… BC aprimora e amplia divulg… 2019-10-16 13:43:33 https://www.b… ""          
 3 Notas à im… https://www… 2019-10-23T12:54:… BC divulga ranking de recla… 2019-10-15 14:31:18 https://www.b… ""          
 4 Notas à im… https://www… 2019-10-23T12:54:… "BC divulga o IBC-Br de ago… 2019-10-14 12:01:02 https://www.b… ""          
 5 Notas à im… https://www… 2019-10-23T12:54:… BC divulgará o IBC-Br de ag… 2019-10-11 14:00:17 https://www.b… ""          
 6 Notas à im… https://www… 2019-10-23T12:54:… BC divulga o Relatório de E… 2019-10-10 12:33:00 https://www.b… ""          
 7 Notas à im… https://www… 2019-10-23T12:54:… BC divulga Indicadores Econ… 2019-10-09 17:42:07 https://www.b… ""          
 8 Notas à im… https://www… 2019-10-23T12:54:… "BC explica Projeto de Lei … 2019-10-07 14:32:23 https://www.b… ""          
 9 Notas à im… https://www… 2019-10-23T12:54:… BC propõe projeto de lei qu… 2019-10-07 14:30:16 https://www.b… ""          
10 Notas à im… https://www… 2019-10-23T12:54:… BC divulga Relatório de Est… 2019-10-07 14:00:04 https://www.b… ""          
# … with 214 more rows
```
