### ISSUE TITLE
Package throws error when loading an json RSS feed

### ISSUE THREAD

**Issue by dctanugi** [RobertMyles/tidyRSS#29]
## Replication steps:
```{R}
library(tidyRSS)
rss <- tidyfeed("https://itunes.apple.com/us/rss/customerreviews/id=1289313118/sortby=mostrecent/json")
```
## Result:
```
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Start tag expected, '<' not found [4]
```

**Comment by RobertMyles** [comment]
Hi,
This error is lower down in xml2, so fixing something in tidyRSS won't have much effect, given that I'm using xml2 for lower-level parsing and have no plans to change that for now. Have you had a look at parsing the content yourself using xml2 or another similar library? When you get these types of parsing errors (usually badly-formatted pages), it's sometimes necessary to dig down deeper yourself.
