### ISSUE TITLE
List of blogs

### ISSUE THREAD

**Issue by alastairrushworth** [RobertMyles/tidyRSS#41]
Hi Rob, for a separate project I've been putting together a list of data science and R related RSS feeds.  Just letting you know about it in case it is useful for testing of `tidyRSS`.  Please feel free to use the list however you like.  

[https://github.com/alastairrushworth/rssfeeds](https://github.com/alastairrushworth/rssfeeds)

Cheers!

Alastair

**Comment by RobertMyles** [comment]
Super helpful, Alastair, appreciate it.
