### ISSUE TITLE
support jsonfeed

### ISSUE THREAD

**Issue by hrbrmstr** [RobertMyles/tidyRSS#6]
https://jsonfeed.org/

IMO it likely makes more sense to support this in one "RSS" pkg than a separate one. I can help with it as well but didn't want to start a new one w/o positing this here first.

**Comment by RobertMyles** [comment]
Ok, that makes sense to me. You're welcome to send a pull request if you think it will be something quick and easy. If it sounds like more work, I can add you as a collaborator, whatever you think best.

**Comment by RobertMyles** [comment]
@jsonbecker @hrbrmstr Any suggestions for how to do this (before I start and maybe lose time trying to understand the format 😄  ) ?

**Comment by RobertMyles** [comment]
Clsed with v1.2.2
