### ISSUE TITLE
Rlang issue

### ISSUE THREAD

**Issue by exploringfinance** [RobertMyles/tidyRSS#61]
I had to go back a version because I kept getting this error. Does not exist in 2.0.4
```

sa = tidyfeed('https://seekingalpha.com/author/schiffgold.xml')
GET request successful. Parsing...

Error in `.f()`:
! Predicate functions must return a single `TRUE` or `FALSE`, not a missing value
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by RobertMyles** [comment]
Sorry to see this happened, @exploringfinance , the new version passed all my tests. I'll have a look at this and see if I can see what's happening.

**Comment by lgnbhl** [comment]
I got the same issue, which broke a function of my R package `BFS` that have tidyRSS as a dependency. Thanks again for your great package!

**Comment by lgnbhl** [comment]
It would be very appreciated if you could fix this bug, so my `BFS` R package can work again.

**Comment by RobertMyles** [comment]
@lgnbhl if you'd like to roll back to version 2.0.4, that should work for you for now, I'll put in a fix for this asap.

**Comment by lgnbhl** [comment]
@RobertMyles Thank you for your quick answer and for working on a fix. Yes, using version 2.0.4 allows my functions to work again.
