### ISSUE TITLE
Searching For Multiple Terms

### ISSUE THREAD

**Issue by swaheera** [RobertMyles/tidyRSS#64]
I am interested in using this to search Google News articles on specific topics. I had the following questions about this:

Suppose I wanted to search for "apple" and "covid" - I used to following code:

```
keyword <- "https://news.google.com/rss/search?q=apple&q=covid&hl=en-IN&gl=IN&ceid=IN:en"

# From the package vignette

google_news <- tidyfeed(
    keyword,
    clean_tags = TRUE,
    parse_dates = TRUE
)

```
1) I am not exactly sure as to how we are supposed to search for multiple terms? Do you use "&", "|" or do you just write both terms together (e.g. "applecovid")?

2) Is there is a way to restrict the dates between which the search will be performed?

3)I have feeling that "IN" stands for "India" - if I want to change this to "Canada", I think I need to replace "IN" with "CAN"? Is this correct?

Your Help is Greatly Appreciated,
Thanks,

**Comment by RobertMyles** [comment]
Hi swaheera, tidyfeed() doesn't work like this, I'm afraid. You'd have to download all the feeds available and then search through them using other tools in R.
