### ISSUE TITLE
Retrieving duration or other custom-named tags

### ISSUE THREAD

**Issue by stees** [RobertMyles/tidyRSS#65]
I'm using tidyRSS to parse podcast RSS and would like to get the duration of each episode together with the title, ID, etc.

Is there a way to do that?

**Comment by RobertMyles** [comment]
Hi stees, there should be, if that field exists. Do you know if podcast rss feeds regularly include this info? Would you have an example or a schema?

**Comment by stees** [comment]
[This one](https://jovemnerd.com.br/feed-nerdcast/) has that information in two forms: `<itunes:duration>` and also like this: `<enclosure url="https://nerdcast.jovemnerd.com.br/vai_te_catar_26.mp3" length="2363" type="audio/mpeg"/>`.

However, most feeds that I checked had only `<itunes:duration>` like [this one](https://feeds.simplecast.com/BqbsxVfO) and [this one](https://historyofjapan.libsyn.com/rss), which already suffices for me.

**Comment by RobertMyles** [comment]
Hi @stees , I've put this in the dev version of the package:

    # remotes::install_github("RobertMyles/tidyRSS")
    dplyr::glimpse(tidyRSS::tidyfeed("https://jovemnerd.com.br/feed-nerdcast/"))
    #> GET request successful. Parsing...
    #> Rows: 1,390
    #> Columns: 14
    #> $ feed_title           <chr> "NerdCast", "NerdCast", "NerdCast", "NerdCast", "…
    #> $ feed_link            <chr> "https://jovemnerd.com.br", "https://jovemnerd.co…
    #> $ feed_description     <chr> "O mundo vira piada no Jovem Nerd", "O mundo vira…
    #> $ feed_language        <chr> "pt-br", "pt-br", "pt-br", "pt-br", "pt-br", "pt-…
    #> $ feed_managing_editor <chr> "feedback@jovemnerd.com.br (Jovem Nerd)", "feedba…
    #> $ feed_pub_date        <dttm> 2022-12-26 05:00:08, 2022-12-26 05:00:08, 2022-1…
    #> $ feed_last_build_date <dttm> 2022-12-27 21:43:25, 2022-12-27 21:43:25, 2022-1…
    #> $ item_title           <chr> "Lá do Bunker 76 - Destaques e desdestaques", "Ca…
    #> $ item_link            <chr> "https://jovemnerd.com.br/nerdcast/la-do-bunker/d…
    #> $ item_description     <chr> "Então é Natal, e o que você fez? Nós do Lá do Bu…
    #> $ item_pub_date        <dttm> 2022-12-26 05:00:08, 2022-12-24 11:26:37, 2022-1…
    #> $ item_guid            <chr> "https://jovemnerd.com.br/nerdcast/la-do-bunker/d…
    #> $ item_category        <list> [], [], [], [], [], [], [], [], [], [], [], [], …
    #> $ item_duration        <chr> "00:49:25", "01:49:59", "01:54:34", "00:00:10", "…

<sup>Created on 2022-12-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Let me know if that works ok for you.

**Comment by stees** [comment]
Works great, many thanks!!
