### ISSUE TITLE
Feed parse error: https://lostcoastoutpost.com/feed/

### ISSUE THREAD

**Issue by jzadra** [RobertMyles/tidyRSS#66]
https://lostcoastoutpost.com/feed/ appears to be a valid feed, but it isn't parsing.

**Comment by RobertMyles** [comment]
Works fine for me, jzadra:

    tidyRSS::tidyfeed("https://lostcoastoutpost.com/feed/")
    #> GET request successful. Parsing...
    #> # A tibble: 25 × 12
    #>    feed_title    feed_…¹ feed_…² feed_…³ feed_pub_date       feed_last_build_d…⁴
    #>    <chr>         <chr>   <chr>   <chr>   <dttm>              <dttm>             
    #>  1 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  2 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  3 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  4 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  5 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  6 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  7 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  8 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #>  9 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #> 10 Lost Coast O… http:/… Lost C… en-us   2022-12-28 07:36:25 2022-12-28 07:36:25
    #> # … with 15 more rows, 6 more variables: item_title <chr>, item_link <chr>,
    #> #   item_description <chr>, item_pub_date <dttm>, item_guid <chr>,
    #> #   item_category <list>, and abbreviated variable names ¹​feed_link,
    #> #   ²​feed_description, ³​feed_language, ⁴​feed_last_build_date

<sup>Created on 2022-12-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
