### ISSUE TITLE
Unable to read xml rss feed https://www.edhat.com/rss.xml

### ISSUE THREAD

**Issue by jzadra** [RobertMyles/tidyRSS#67]
https://www.edhat.com/rss.xml

Sorry if this isn't intended to be read by tidyRSS, I wasn't quite clear on it's xml abilities.

**Comment by chainsawriot** [comment]
Not a valid feed

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.edhat.com%2Frss.xml

**Comment by RobertMyles** [comment]
Closing this, thanks for the input @chainsawriot
