### ISSUE TITLE
make the *_parse functions exported?

### ISSUE THREAD

**Issue by rmflight** [RobertMyles/tidyRSS#68]
I have a situation where I want to parse a "local" rss feed (the quarto blog generated index.xml).

The `httr::GET()` fails on a local file, but `tidyRSS::rss_parse()` works just fine on the on disk index.xml file, but it's not exposed to other users.

I thought about putting it into my own package, but then I've copied over a rather large chunk of the package functions, which seems pointless. It seemed easier to just ask if you could export the various *_parse functions instead.

I also get it if it seems like too much work to support having them exported.

**Comment by RobertMyles** [comment]
Interesting idea, @rmflight , I'll consider that for the next version.

**Comment by rmflight** [comment]
Thanks @RobertMyles , appreciate even considering it.
