### ISSUE TITLE
Problem reading feeds

### ISSUE THREAD

**Issue by student0129** [RobertMyles/tidyRSS#7]
Hi, 

I have used this package before and it worked for some feeds. I say some because feeds are finicky. However, the package suddenly stopped working. For example, I cannot get access to feeds such as https://www.federalreserve.gov/feeds/press_orders.xml, https://public.govdelivery.com/topics/USFDIC_11/feed.rss, or https://www.sec.gov/rss/investor/alerts.

The code I use is very simple:
library(tidyRSS)
tidyfeed("https://www.federalreserve.gov/feeds/press_all.xml", result = "all")

And here is the error I receive:
Error in withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning")) : 
  This page does not appear to be a suitable feed. Have you checked that you entered the url correctly?
If you are certain that this is a valid rss feed, please file an issue at: https://github.com/RobertMyles/tidyRSS/issues. Please note that the feed may also be undergoing maintenance.

The site is not down since I can access the feed from Python or using other R packages. 

I would appreciate if you can look into this. 

Thank you!

**Comment by RobertMyles** [comment]
Hi @student0129 . Can you try `httr::GET()` on these feeds? If it gives you some type of SSL error (such as `SSLRead() return error -9806`), this might work:  

```
$ brew remove git
$ brew remove curl

$ brew install openssl
$ brew install --with-openssl curl
$ brew install --with-brewed-curl --with-brewed-openssl git
```

**Comment by RobertMyles** [comment]
These work now: 

`tidyfeed("https://www.federalreserve.gov/feeds/press_orders.xml")` gives: 


```
# A tibble: 12 x 8
                                  feed_title                                      feed_link
                                       <chr>                                          <chr>
 1 FRB: Press Release - Banking Applications https://www.federalreserve.gov/feeds/feeds.htm
 2 FRB: Press Release - Banking Applications https://www.federalreserve.gov/feeds/feeds.htm
 3 FRB: Press Release - Banking Applications https://www.federalreserve.gov/feeds/feeds.htm
 4 FRB: Press Release - Banking Applications https://www.federalreserve.gov/feeds/feeds.htm
```
`tidyfeed("https://public.govdelivery.com/topics/USFDIC_11/feed.rss")`:

```
# A tibble: 25 x 7
                             feed_title                                 feed_link
                                  <chr>                                     <chr>
 1 FDIC Board Meetings - Recent Updates http://www.fdic.gov/news/board/index.html
 2 FDIC Board Meetings - Recent Updates http://www.fdic.gov/news/board/index.html
 3 FDIC Board Meetings - Recent Updates http://www.fdic.gov/news/board/index.html
```

```
> tidyfeed("https://www.sec.gov/rss/investor/alerts")
xmlXPathEval: evaluation failed
# A tibble: 25 x 8
                      feed_title                               feed_link
                           <chr>                                   <chr>
 1 Investor Alerts and Bulletins https://www.sec.gov/rss/investor/alerts
 2 Investor Alerts and Bulletins https://www.sec.gov/rss/investor/alerts
 3 Investor Alerts and Bulletins https://www.sec.gov/rss/investor/alerts
 4 Investor Alerts and Bulletins https://www.sec.gov/rss/investor/alerts
```

(showing just a snippet of each)
