### ISSUE TITLE
Rethink testing strategy

### ISSUE THREAD

**Issue by jimhester** [RobertMyles/tidyRSS#9]
The current method of testing for **tidyRSS** produces non-deterministic results because a different feed is used each time tests are run. This makes test failures hard to reproduce and spurious, when testing on CRAN or elsewhere.

https://github.com/RobertMyles/tidyRSS/blob/55e52555d65584a46eee54edf3d233b8c82ffecb/tests/testthat/test.feeds.R#L8-L12

This is made doubly bad because currently two of the feeds are no longer valid, so tests will fail if these examples happen to occur.

``` r
tidyRSS::tidyfeed(tidyRSS::feeds$feeds[[12]])
#> Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, : xmlParseEntityRef: no name [68]
tidyRSS::tidyfeed(tidyRSS::feeds$feeds[[28]])
#> Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html, : Premature end of data in tag lastBuildDate line 8 [77]
```
> Created on 2018-01-24 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

In general relying on external network resources for tests is problematic, consider instead including a few (truncated) feeds in your package instead that could be used for testing.

If you do want to continue using external resources please use `testthat::skip_for_cran()` to disable these tests on CRAN.

**Comment by RobertMyles** [comment]
Ok, Jim, will do, thanks for the heads-up.
